import { AnnouncementBadge } from '@/components/elements/announcement-badge'
import { ButtonLink, PlainButtonLink } from '@/components/elements/button'
import { InstallCommand } from '@/components/elements/install-command'
import { Link } from '@/components/elements/link'
import { Logo, LogoGrid } from '@/components/elements/logo-grid'
import { Main } from '@/components/elements/main'
import { Screenshot } from '@/components/elements/screenshot'
import { ChevronIcon } from '@/components/icons/chevron-icon'
import { GitHubIcon } from '@/components/icons/social/github-icon'
import { XIcon } from '@/components/icons/social/x-icon'
import { YouTubeIcon } from '@/components/icons/social/youtube-icon'
import { BrandCard, BrandsCardsMultiColumn } from '@/components/sections/brands-cards-multi-column'
import { CallToActionSimple } from '@/components/sections/call-to-action-simple'
import {
  Feature,
  FeaturesStackedAlternatingWithDemos,
} from '@/components/sections/features-stacked-alternating-with-demos'
import {
  FooterLink,
  FooterWithLinksAndSocialIcons,
  SocialLink,
} from '@/components/sections/footer-with-links-and-social-icons'
import { HeroCenteredWithDemo } from '@/components/sections/hero-centered-with-demo'
import {
  NavbarLink,
  NavbarLogo,
  NavbarWithLogoActionsAndLeftAlignedLinks,
} from '@/components/sections/navbar-with-logo-actions-and-left-aligned-links'
import { Stat, StatsWithGraph } from '@/components/sections/stats-with-graph'
import { TestimonialTwoColumnWithLargePhoto } from '@/components/sections/testimonial-two-column-with-large-photo'

export default function Page() {
  return (
    <>
      <NavbarWithLogoActionsAndLeftAlignedLinks
        id="navbar"
        logo={
          <NavbarLogo href="#">
            <img
              src="https://assets.tailwindplus.com/logos/oatmeal-instrument.svg?color=mist-950"
              alt="Oatmeal"
              className="dark:hidden"
              width={85}
              height={28}
            />
            <img
              src="https://assets.tailwindplus.com/logos/oatmeal-instrument.svg?color=white"
              alt="Oatmeal"
              className="not-dark:hidden"
              width={85}
              height={28}
            />
          </NavbarLogo>
        }
        links={
          <>
            <NavbarLink href="#">Pricing</NavbarLink>
            <NavbarLink href="#">About</NavbarLink>
            <NavbarLink href="#">Docs</NavbarLink>
            <NavbarLink href="#" className="sm:hidden">
              Log in
            </NavbarLink>
          </>
        }
        actions={
          <>
            <PlainButtonLink href="#" className="max-sm:hidden">
              Log in
            </PlainButtonLink>
            <ButtonLink href="#">Get started</ButtonLink>
          </>
        }
      />

      <Main>
        {/* Hero */}
        <HeroCenteredWithDemo
          id="hero"
          eyebrow={<AnnouncementBadge href="#" text="Oatmeal raises 80M Series A funding" cta="Learn more" />}
          headline="Customer support that feels like a conversation."
          subheadline={
            <p>
              Simplify your shared inbox, collaborate effortlessly, and give every customer a reply that feels personal
              — even if it was generated by a bot.
            </p>
          }
          cta={<InstallCommand className="min-w-xs" snippet="npm install oatmeal" />}
          demo={
            <>
              <Screenshot className="rounded-md lg:hidden" wallpaper="blue" placement="bottom-right">
                <img
                  src="https://assets.tailwindplus.com/screenshots/1.webp?left=1670&top=1408"
                  alt=""
                  width={1670}
                  height={1408}
                  className="md:hidden dark:hidden"
                />
                <img
                  src="https://assets.tailwindplus.com/screenshots/1.webp?left=1670&top=1408&color=mist"
                  alt=""
                  width={1670}
                  height={1408}
                  className="not-dark:hidden md:hidden"
                />
                <img
                  src="https://assets.tailwindplus.com/screenshots/1.webp?left=2000&top=1408"
                  alt=""
                  width={2000}
                  height={1408}
                  className="max-md:hidden dark:hidden"
                />
                <img
                  src="https://assets.tailwindplus.com/screenshots/1.webp?left=2000&top=1408&color=mist"
                  alt=""
                  width={2000}
                  height={1408}
                  className="not-dark:hidden max-md:hidden"
                />
              </Screenshot>
              <Screenshot className="rounded-lg max-lg:hidden" wallpaper="blue" placement="bottom">
                <img
                  className="dark:hidden"
                  src="https://assets.tailwindplus.com/screenshots/1.webp"
                  alt=""
                  width={3440}
                  height={1990}
                />
                <img
                  className="not-dark:hidden"
                  src="https://assets.tailwindplus.com/screenshots/1.webp?color=mist"
                  alt=""
                  width={3440}
                  height={1990}
                />
              </Screenshot>
            </>
          }
          footer={
            <LogoGrid>
              <Logo>
                <img
                  src="https://assets.tailwindplus.com/logos/9.svg?color=black&height=32"
                  className="dark:hidden"
                  alt=""
                  width={51}
                  height={32}
                />
                <img
                  src="https://assets.tailwindplus.com/logos/9.svg?color=white&height=32"
                  className="not-dark:hidden"
                  alt=""
                  width={51}
                  height={32}
                />
              </Logo>
              <Logo>
                <img
                  src="https://assets.tailwindplus.com/logos/10.svg?color=black&height=32"
                  className="dark:hidden"
                  alt=""
                  width={70}
                  height={32}
                />
                <img
                  src="https://assets.tailwindplus.com/logos/10.svg?color=white&height=32"
                  className="not-dark:hidden"
                  alt=""
                  width={70}
                  height={32}
                />
              </Logo>
              <Logo>
                <img
                  src="https://assets.tailwindplus.com/logos/11.svg?color=black&height=32"
                  className="dark:hidden"
                  alt=""
                  width={100}
                  height={32}
                />
                <img
                  src="https://assets.tailwindplus.com/logos/11.svg?color=white&height=32"
                  className="not-dark:hidden"
                  alt=""
                  width={100}
                  height={32}
                />
              </Logo>
              <Logo>
                <img
                  src="https://assets.tailwindplus.com/logos/12.svg?color=black&height=32"
                  className="dark:hidden"
                  alt=""
                  width={85}
                  height={32}
                />
                <img
                  src="https://assets.tailwindplus.com/logos/12.svg?color=white&height=32"
                  className="not-dark:hidden"
                  alt=""
                  width={85}
                  height={32}
                />
              </Logo>
              <Logo>
                <img
                  src="https://assets.tailwindplus.com/logos/13.svg?color=black&height=32"
                  className="dark:hidden"
                  alt=""
                  width={75}
                  height={32}
                />
                <img
                  src="https://assets.tailwindplus.com/logos/13.svg?color=white&height=32"
                  className="not-dark:hidden"
                  alt=""
                  width={75}
                  height={32}
                />
              </Logo>
              <Logo>
                <img
                  src="https://assets.tailwindplus.com/logos/8.svg?color=black&height=32"
                  className="dark:hidden"
                  alt=""
                  width={85}
                  height={32}
                />
                <img
                  src="https://assets.tailwindplus.com/logos/8.svg?color=white&height=32"
                  className="not-dark:hidden"
                  alt=""
                  width={85}
                  height={32}
                />
              </Logo>
            </LogoGrid>
          }
        />

        {/* Features */}
        <FeaturesStackedAlternatingWithDemos
          id="features"
          headline="Everything you need to deliver personal, organized, and delightful support."
          subheadline={
            <p>
              Work smarter, reply faster, and keep every customer conversation right where it belongs — in one simple
              inbox, where you can ignore it.
            </p>
          }
          features={
            <>
              <Feature
                headline="Shared Inbox"
                subheadline={<p>Manage support emails together in real time — no more support email hot potato.</p>}
                cta={
                  <Link href="#">
                    Learn more <ChevronIcon />
                  </Link>
                }
                demo={
                  <Screenshot wallpaper="blue" placement="bottom-right">
                    <img
                      src="https://assets.tailwindplus.com/screenshots/1.webp?left=1200&top=736"
                      alt=""
                      className="bg-white/75 sm:hidden dark:hidden"
                      width={1200}
                      height={736}
                    />
                    <img
                      src="https://assets.tailwindplus.com/screenshots/1.webp?left=1200&top=736&color=mist"
                      alt=""
                      width={1200}
                      height={736}
                      className="bg-black/75 not-dark:hidden sm:hidden"
                    />
                    <img
                      src="https://assets.tailwindplus.com/screenshots/1.webp?left=1500&top=680"
                      alt=""
                      className="bg-white/75 max-sm:hidden lg:hidden dark:hidden"
                      width={1500}
                      height={680}
                    />
                    <img
                      width={1500}
                      height={680}
                      src="https://assets.tailwindplus.com/screenshots/1.webp?left=1500&top=680&color=mist"
                      alt=""
                      className="bg-black/75 not-dark:hidden max-sm:hidden lg:hidden"
                    />
                    <img
                      src="https://assets.tailwindplus.com/screenshots/1.webp?left=1500&top=1240"
                      alt=""
                      className="bg-white/75 max-lg:hidden dark:hidden"
                      width={1500}
                      height={1240}
                    />
                    <img
                      width={1500}
                      height={1240}
                      src="https://assets.tailwindplus.com/screenshots/1.webp?left=1500&top=1240&color=mist"
                      alt=""
                      className="bg-black/75 not-dark:hidden max-lg:hidden"
                    />
                  </Screenshot>
                }
              />
              <Feature
                headline="Collision Detection"
                subheadline={<p>See when a teammate is replying before you hit send. Goodbye duplicate replies.</p>}
                cta={
                  <Link href="#">
                    Learn more <ChevronIcon />
                  </Link>
                }
                demo={
                  <Screenshot wallpaper="purple" placement="top-left">
                    <img
                      src="https://assets.tailwindplus.com/screenshots/1.webp?right=1200&bottom=736"
                      alt=""
                      className="bg-white/75 sm:hidden dark:hidden"
                      width={1200}
                      height={736}
                    />
                    <img
                      src="https://assets.tailwindplus.com/screenshots/1.webp?right=1200&bottom=736&color=mist"
                      alt=""
                      width={1200}
                      height={736}
                      className="bg-black/75 not-dark:hidden sm:hidden"
                    />
                    <img
                      src="https://assets.tailwindplus.com/screenshots/1.webp?right=1500&bottom=680"
                      alt=""
                      className="bg-white/75 max-sm:hidden lg:hidden dark:hidden"
                      width={1500}
                      height={680}
                    />
                    <img
                      src="https://assets.tailwindplus.com/screenshots/1.webp?right=1500&bottom=680&color=mist"
                      alt=""
                      width={1500}
                      height={680}
                      className="bg-black/75 not-dark:hidden max-sm:hidden lg:hidden"
                    />
                    <img
                      src="https://assets.tailwindplus.com/screenshots/1.webp?right=1500&bottom=1240"
                      alt=""
                      className="bg-white/75 max-lg:hidden dark:hidden"
                      width={1500}
                      height={1240}
                    />
                    <img
                      src="https://assets.tailwindplus.com/screenshots/1.webp?right=1500&bottom=1240&color=mist"
                      width={1500}
                      height={1240}
                      alt=""
                      className="bg-black/75 not-dark:hidden max-lg:hidden"
                    />
                  </Screenshot>
                }
              />
              <Feature
                headline="Inbox Agent"
                subheadline={<p>Get valuable context without having to read through a long thread.</p>}
                cta={
                  <Link href="#">
                    Learn more <ChevronIcon />
                  </Link>
                }
                demo={
                  <Screenshot wallpaper="brown" placement="bottom-left">
                    <img
                      src="https://assets.tailwindplus.com/screenshots/1.webp?right=1200&top=736"
                      alt=""
                      className="bg-white/75 sm:hidden dark:hidden"
                      width={1200}
                      height={736}
                    />
                    <img
                      src="https://assets.tailwindplus.com/screenshots/1.webp?right=1200&top=736&color=mist"
                      alt=""
                      width={1200}
                      height={736}
                      className="bg-black/75 not-dark:hidden sm:hidden"
                    />
                    <img
                      src="https://assets.tailwindplus.com/screenshots/1.webp?right=1500&top=680"
                      alt=""
                      className="bg-white/75 max-sm:hidden lg:hidden dark:hidden"
                      width={1500}
                      height={680}
                    />
                    <img
                      src="https://assets.tailwindplus.com/screenshots/1.webp?right=1500&top=680&color=mist"
                      alt=""
                      width={1500}
                      height={680}
                      className="bg-black/75 not-dark:hidden max-sm:hidden lg:hidden"
                    />
                    <img
                      src="https://assets.tailwindplus.com/screenshots/1.webp?right=1500&top=1240"
                      alt=""
                      className="bg-white/75 max-lg:hidden dark:hidden"
                      width={1500}
                      height={1240}
                    />
                    <img
                      src="https://assets.tailwindplus.com/screenshots/1.webp?right=1500&top=1240&color=mist"
                      alt=""
                      width={1500}
                      height={1240}
                      className="bg-black/75 not-dark:hidden max-lg:hidden"
                    />
                  </Screenshot>
                }
              />
            </>
          }
        />

        {/* Brands */}
        <BrandsCardsMultiColumn
          id="brands"
          eyebrow="Backed by the best"
          headline="Funded by leading investors."
          subheadline={
            <p>
              Oatmeal is backed by investors with decades of experience building the world's most boring and predictable
              B2B SaaS.
            </p>
          }
        >
          <BrandCard
            logo={
              <>
                <img
                  src="https://assets.tailwindplus.com/logos/15.svg?color=black&width=110"
                  className="dark:hidden"
                  alt=""
                  width={124}
                  height={32}
                />
                <img
                  src="https://assets.tailwindplus.com/logos/15.svg?color=white&width=110"
                  className="not-dark:hidden"
                  alt=""
                  width={124}
                  height={32}
                />
              </>
            }
            text="Focused capital for founders building the next generation of pyramid shaped businesses."
            footnote="Investor in Anomaly, Concise, Haptic and more."
          />
          <BrandCard
            logo={
              <>
                <img
                  src="https://assets.tailwindplus.com/logos/16.svg?color=black&width=120"
                  className="dark:hidden"
                  alt=""
                  width={146}
                  height={32}
                />
                <img
                  src="https://assets.tailwindplus.com/logos/16.svg?color=white&width=120"
                  className="not-dark:hidden"
                  alt=""
                  width={146}
                  height={32}
                />
              </>
            }
            text="Serving as a tax-efficiency vehicle for investors waiting to move to a tax haven."
            footnote="Investor in Quirk, Looply, Pine Labs and more."
          />
          <BrandCard
            logo={
              <>
                <img
                  src="https://assets.tailwindplus.com/logos/14.svg?color=black&width=80"
                  className="dark:hidden"
                  alt=""
                  width={106}
                  height={32}
                />
                <img
                  src="https://assets.tailwindplus.com/logos/14.svg?color=white&width=80"
                  className="not-dark:hidden"
                  alt=""
                  width={106}
                  height={32}
                />
              </>
            }
            text="Investing in potentially volatile bubble markets at an early stage."
            footnote="Investor in Artifact, Umbra, vivid.ai and more."
          />
        </BrandsCardsMultiColumn>

        {/* Testimonial */}
        <TestimonialTwoColumnWithLargePhoto
          id="testimonial"
          quote={
            <p>
              Ever since we started using Oatmeal, our customer satisfaction scores have skyrocketed. The personal touch
              that their human-AI hybrid support provides is unparalleled.
            </p>
          }
          img={
            <img
              src="https://assets.tailwindplus.com/avatars/16.webp?w=1400&h=1000"
              alt=""
              className="not-dark:bg-white/75 dark:bg-black/75"
              width={1400}
              height={1000}
            />
          }
          name="Lynn Marshall"
          byline="Founder at Pine Labs"
        />

        {/* Stats */}
        <StatsWithGraph
          id="stats"
          eyebrow="Built for scale"
          headline="The inbox powering customer conversations everywhere."
          subheadline={
            <p>
              Oatmeal helps teams deliver personal, organized, and fast customer support across the world. From small
              startups to enterprise teams, we process millions of messages each month — using a massive network of low
              wage workers stationed around the globe.
            </p>
          }
        >
          <Stat stat="2M+" text="Emails manually processed every week across thousands of teams." />
          <Stat stat="99.98%" text="Uptime — because your customers never stop complaining." />
        </StatsWithGraph>

        {/* Call To Action */}
        <CallToActionSimple
          id="call-to-action"
          headline="Ready to make customer support feel simple again?"
          subheadline={
            <p>
              Join hundreds of teams using Oatmeal to deliver faster, friendlier email support — using a massive network
              of low wage workers stationed around the globe
            </p>
          }
          cta={
            <div className="flex items-center gap-4">
              <ButtonLink href="#" size="lg">
                Start free trial
              </ButtonLink>

              <PlainButtonLink href="#" size="lg">
                Book a demo <ChevronIcon />
              </PlainButtonLink>
            </div>
          }
        />
      </Main>

      <FooterWithLinksAndSocialIcons
        id="footer"
        links={
          <>
            <FooterLink href="#">About</FooterLink>
            <FooterLink href="#">Careers</FooterLink>
            <FooterLink href="#">Blog</FooterLink>
            <FooterLink href="#">Help Center</FooterLink>
            <FooterLink href="#">Press Kit</FooterLink>
            <FooterLink href="#">Privacy Policy</FooterLink>
          </>
        }
        socialLinks={
          <>
            <SocialLink href="https://x.com" name="X">
              <XIcon />
            </SocialLink>
            <SocialLink href="https://github.com" name="GitHub">
              <GitHubIcon />
            </SocialLink>
            <SocialLink href="https://www.youtube.com" name="YouTube">
              <YouTubeIcon />
            </SocialLink>
          </>
        }
        fineprint="© 2025 Oatmeal, Inc."
      />
    </>
  )
}
